### ISSUE TITLE
'ignorePrescriptionDate' does not exist on type 'Invoice'.

### ISSUE THREAD

**Issue by cebamps** [antoinepairet/icc-api#42]
efact-util.ts references the property but it not defined in the Invoice model from the fhc-api dependency.

> ERROR in libs/icure-api/src/lib/icc-x-api/utils/efact-util.ts(129,11): error TS2339: Property 'ignorePrescriptionDate' does not exist on type 'Invoice'.

Introduced in cd0bfa61f1526e65a960cbfff4f8dbd4501d7f73

**Comment by cebamps** [comment]
Haven't seen that error in a while. It must have been fixed :)
